# Generated by Django 3.2.4 on 2021-07-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('course', models.CharField(choices=[('Desserts', 'Desserts'), ('Starters Dish', 'Starters Dish'), ('Main Course', 'Main Course'), ('Cold Drinks', 'Cold Drinks')], max_length=50)),
                ('status', models.CharField(choices=[('Disabled', 'Disabled'), ('Enabled', 'Enabled')], max_length=50)),
                ('content_description', models.TextField()),
                ('base_price', models.FloatField()),
                ('sale_price', models.FloatField(default=models.FloatField())),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('num_order', models.IntegerField(default=0)),
            ],
        ),
    ]
