# Generated by Django 3.2.4 on 2021-07-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_rename_in_stock_food_stock_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='menu/'),
        ),
    ]
