# Generated by Django 3.2.4 on 2021-06-30 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=10)),
                ('salary', models.IntegerField()),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Chef', 'Chef'), ('Delivery Boy', 'Delivery Boy')], max_length=30)),
                ('staff_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('area', models.CharField(default='', max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('orders', models.IntegerField(default=0)),
                ('total_sale', models.IntegerField(default=0)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
